# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

remote_theme             : "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin    : "dark" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "ko-KR"
title                    : "Kim Gabe's Ds blog"
title_separator          : "|"
subtitle                 : Andante GraziosoğŸµ # site tagline that appears below site title in masthead
name                     : "Kim Gabe"
description              : "Gabeì˜ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤."
url                      : "https://Kimgabe.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : #"Kimgabe/Kimgabe.github.io" # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : /assets/img/favicons/home-logo.png # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
breadcrumbs              : true # true, false (default)
words_per_minute         : 200
date_format              : "%Y-%m-%d, %H:%M"
paginate                 : 5z
paginate_path            : /page/:num/
# pagination               :
#   enabled                : true
#   per_page               : 5
#   permalink              : '/page/:num/'
#   sort_field             : 'last_modified_at'
#   sort_reverse           : true
#   category               : 'posts'
#   trail                  : 
#     before               : 2
#     after                : 2

comments:
  provider               : "disque" # false (default), "disqus", "discourse", "facebook", "staticman_v2", "staticman", "utterances", "giscus", "custom"
  disqus:
    shortname            : Kim gabe's Github blog
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : #"github-dark" # "github-light" (default), "github-dark"
    issue_term           : #"pathname" # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"

reCaptcha:
  siteKey                : # "6LdRBykTAAAAAFB46MnIu6ixuxwu9W1ihFF8G60Q"
  secret                 : # "PznnZGu3P6eTHRPLORniSq+J61YEf+A9zmColXDM5icqF49gbunH51B8+h+i2IvewpuxtA9TFoK68TuhUp/X3YKmmqhXasegHYabY50fqF9nJh9npWNhvITdkQHeaOqnFXUIwxfiEeUt49Yoa2waRR7a5LdRAP3SVM8hz0KIBT4="

atom_feed:
  path                   : # blank (default) uses feed.xml

search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : lunr # lunr (default), algolia
#algolia:
#  application_id         : QB6HVGBSBA # YOUR_APPLICATION_ID
#  index_name             : minimal_mistakes # YOUR_INDEX_NAME
#  search_only_api_key    : 9d5014e5bbc77372547bce778dfa5663 # YOUR_SEARCH_ONLY_API_KEY
#  powered_by             : true # true (default), false
#  files_to_exclude:
#    - _posts/2017-11-28-post-exclude-search.md

# SEO Related
google_site_verification : # Replace this with your ID, or delete
bing_site_verification   :
naver_site_verification  : "0bcef25e94264a9e1c88c9d2b553e516e9816596"
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "_wonseok_"
facebook:
  username               : &facebook "wonseoko"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/_wonseok_"
    - "https://www.facebook.com/wonseoko"

# Analytics
analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-S8SVCTHDH2" # Replace this with your ID, or delete
    anonymize_ip         : # true, false (default)


# Site Author
author:
  name             : "Kim Gabe"
  avatar           : assets/img/gabe_profile.png # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : '"Knowledge without application is meaningless. True learning lies in educating and empowering others."' 
  location         : "Somewhere"
  email            :
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Kimgabe"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      #url: "https://www.instagram.com/koomo_the_cat/"


# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Kimgabe"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      #url: "https://www.instagram.com/koomo_the_cat/"
    - label: "Velog"
      icon: "fab fa-vimeo" #ëª¨ì–‘ ë¹„ìŠ·í•œê±¸ë¡œ ì…ë ¥í•´ë‘ 
      # url: 


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - x-pages
  - x-posts
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/
  recipes:
    output: true
    permalink: /:collection/:path/
  pets:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/


# Defaults
# ê¸°ë³¸ ì„¤ì •ë“¤: ì´ ì„¤ì •ì€ íŠ¹ì • ìœ í˜•ì˜ í¬ìŠ¤íŠ¸ë‚˜ í˜ì´ì§€ì— ëŒ€í•œ ê¸°ë³¸ ê°’ì„ ì„¤ì •í•©ë‹ˆë‹¤.
defaults:
  # _posts
  # ê¸°ë³¸ í¬ìŠ¤íŠ¸ ì„¤ì •
  - scope:
      path: "" # ê²½ë¡œ ì„¤ì •. ì—¬ê¸°ì„œëŠ” ëª¨ë“  ê²½ë¡œì— ëŒ€í•´ ì ìš©ë©ë‹ˆë‹¤.
      type: posts # í¬ìŠ¤íŠ¸ ìœ í˜•
    values:
      layout: single # ë ˆì´ì•„ì›ƒ ìœ í˜•
      author_profile: true # ì €ì í”„ë¡œí•„ í‘œì‹œ ì—¬ë¶€
      read_time: true # ì½ëŠ” ì‹œê°„ í‘œì‹œ ì—¬ë¶€
      show_date: true # ë‚ ì§œ í‘œì‹œ ì—¬ë¶€
      comments: true # ëŒ“ê¸€ í‘œì‹œ ì—¬ë¶€
      share: true # ê³µìœ  ë²„íŠ¼ í‘œì‹œ ì—¬ë¶€
      related: true # ê´€ë ¨ í¬ìŠ¤íŠ¸ í‘œì‹œ ì—¬ë¶€
      toc: true # ëª©ì°¨ í‘œì‹œ ì—¬ë¶€
      toc_sticky: true # ëª©ì°¨ ê³ ì • ì—¬ë¶€
  # ... (ì´í•˜ ë‚´ìš©ì€ ìœ„ì™€ ìœ ì‚¬í•œ í˜•íƒœë¡œ ë‹¤ì–‘í•œ ìœ í˜•ì˜ í¬ìŠ¤íŠ¸ë‚˜ í˜ì´ì§€ì— ëŒ€í•œ ê¸°ë³¸ ì„¤ì •ì…ë‹ˆë‹¤.)

# Sass/SCSS
# Sass/SCSS ê´€ë ¨ ì„¤ì •
sass:
  sass_dir: _sass # Sass íŒŒì¼ ë””ë ‰í† ë¦¬ ìœ„ì¹˜
  style: compressed # ì¶œë ¥ ìŠ¤íƒ€ì¼ ì„¤ì • (ì—¬ê¸°ì„œëŠ” ì••ì¶•ëœ í˜•íƒœë¡œ ì„¤ì •)

# Outputting
# ì¶œë ¥ ì„¤ì •
permalink: /:categories/:title/ # ê³ ìœ  ë§í¬ í˜•ì‹ ì„¤ì •
timezone: Asia/Seoul # ì‹œê°„ëŒ€ ì„¤ì •

# Plugins (previously gems:)
# ì‚¬ìš©í•˜ëŠ” í”ŒëŸ¬ê·¸ì¸ ë¦¬ìŠ¤íŠ¸
plugins:
  - jekyll-paginate
  - ...

# mimic GitHub Pages with --safe
# GitHub Pagesì˜ --safe ì˜µì…˜ê³¼ ìœ ì‚¬í•œ ì„¤ì •
whitelist:
  - jekyll-paginate
  - ...

# Archives
# ì•„ì¹´ì´ë¸Œ ê´€ë ¨ ì„¤ì •
category_archive:
  type: liquid # ì•„ì¹´ì´ë¸Œ ìœ í˜• ì„¤ì •
  path: /categories/ # ì¹´í…Œê³ ë¦¬ ì•„ì¹´ì´ë¸Œ ê²½ë¡œ ì„¤ì •
tag_archive:
  type: liquid # ì•„ì¹´ì´ë¸Œ ìœ í˜• ì„¤ì •
  path: /tags/ # íƒœê·¸ ì•„ì¹´ì´ë¸Œ ê²½ë¡œ ì„¤ì •

# HTML Compression
# HTML ì••ì¶• ê´€ë ¨ ì„¤ì •
compress_html:
  clippings: all # ëª¨ë“  HTMLì„ ì••ì¶•
  ignore:
    envs: development # ê°œë°œ í™˜ê²½ì—ì„œëŠ” ì••ì¶•í•˜ì§€ ì•ŠìŒ

